# coding: utf-8
houdd_user_root = HouddUser.create(:name=>'吉田松陰', :admin_flg=>true, :login_id=>'admin', :login_pw=>'admin', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
houdd_user_test1 = HouddUser.create(:name=>'有吉熊次郎', :admin_flg=>false, :login_id=>'ariyoshi', :login_pw=>'ariyoshi', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
houdd_user_test2 = HouddUser.create(:name=>'飯田正伯', :admin_flg=>false, :login_id=>'iida', :login_pw=>'iida', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'wepon', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'armor', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'potion', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'trap', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'wepon', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'armor', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'potion', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'trap', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'wepon', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'armor', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'potion', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'trap', :level=>1, :allotment=>0, :invested_point=>0)
terrain_plain = Terrain.create(:symbol=>'plain', :name=>'平地', :food=>1, :production=>0, :money=>0, :frequency_rate=>45, :continuity_mod=>0)
terrain_woods = Terrain.create(:symbol=>'woods', :name=>'森林', :food=>0, :production=>1, :money=>0, :frequency_rate=>20, :continuity_mod=>20)
terrain_mountain = Terrain.create(:symbol=>'mountain', :name=>'山岳', :food=>0, :production=>0, :money=>0, :frequency_rate=>15, :continuity_mod=>15)
terrain_desert = Terrain.create(:symbol=>'desert', :name=>'砂漠', :food=>0, :production=>0, :money=>0, :frequency_rate=>10, :continuity_mod=>15)
terrain_sea = Terrain.create(:symbol=>'sea', :name=>'海洋', :food=>0, :production=>0, :money=>0, :frequency_rate=>10, :continuity_mod=>20)
sp_resource_iron = SpResource.create(:terrain=>terrain_mountain, :symbol=>'iron', :name=>'鉄', :food=>0, :production=>1, :money=>0, :frequency_rate=>3)
sp_resource_gold = SpResource.create(:terrain=>terrain_mountain, :symbol=>'gold', :name=>'金', :food=>0, :production=>0, :money=>3, :frequency_rate=>1)
sp_resource_fur = SpResource.create(:terrain=>terrain_woods, :symbol=>'fur', :name=>'毛皮', :food=>0, :production=>1, :money=>0, :frequency_rate=>2)
sp_resource_cotton = SpResource.create(:terrain=>terrain_plain, :symbol=>'cotton', :name=>'綿花', :food=>0, :production=>1, :money=>0, :frequency_rate=>3)
sp_resource_fish = SpResource.create(:terrain=>terrain_sea, :symbol=>'fish', :name=>'魚', :food=>2, :production=>0, :money=>0, :frequency_rate=>5)
Construction.create(:terrain=>terrain_plain, :symbol=>'farm', :name=>'農場', :food=>2, :production=>0, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_mountain, :symbol=>'mine', :name=>'鉱山', :food=>0, :production=>2, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'wepon', :name=>'武器工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'armor', :name=>'防具工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'potion', :name=>'ポーション工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'trading', :name=>'交易所', :food=>0, :production=>0, :money=>1, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_sea, :symbol=>'port', :name=>'港', :food=>2, :production=>0, :money=>0, :rq_prod_point=>50, :rq_days=>20)
MiniMap.create(:houdd_user=>houdd_user_root, :name=>'エデン', :size=>7, :hq_flg=>true, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test1, :name=>'新木', :size=>10, :hq_flg=>true, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test1, :name=>'歌里', :size=>6, :hq_flg=>false, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test2, :name=>'牛島', :size=>10, :hq_flg=>true, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test2, :name=>'江川', :size=>6, :hq_flg=>false, :type_symbol=>'plain')
BodyPart.create(:name=>'手')
BodyPart.create(:name=>'足')
BodyPart.create(:name=>'胴')
item_category_sword = ItemCategory.create(:type_sym=>'wepon', :name=>'剣', :body_part_id=>1, :rq_slot_num=>1)
item_category_stick = ItemCategory.create(:type_sym=>'wepon', :name=>'棍棒', :body_part_id=>1, :rq_slot_num=>1)
item_info_dagger = ItemInfo.create(:item_category=>item_category_sword, :size=>1, :weight_level=>1, :name=>'短剣', :max_dp=>100, :rq_prod_point=>100, :research_level=>2)
item_info_short_sword = ItemInfo.create(:item_category=>item_category_sword, :size=>2, :weight_level=>2, :name=>'小剣', :max_dp=>100, :rq_prod_point=>100, :research_level=>2)
item_info_club = ItemInfo.create(:item_category=>item_category_sword, :size=>1, :weight_level=>2, :name=>'棍棒', :max_dp=>50, :rq_prod_point=>30, :research_level=>1)
ItemSpResourceInv.create(:item_info=>item_info_dagger, :sp_resource=>sp_resource_iron)
ItemSpResourceInv.create(:item_info=>item_info_short_sword, :sp_resource=>sp_resource_iron)
status_mod_cut1 = StatusMod.create(:name=>'切り1', :hit_accuracy=>70, :d_range=>1, :x_range=>1, :hp_damage=>500, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
status_mod_cut2 = StatusMod.create(:name=>'切り2', :hit_accuracy=>70, :d_range=>1, :x_range=>1, :hp_damage=>1000, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
status_mod_beat1 = StatusMod.create(:name=>'叩き1', :hit_accuracy=>60, :d_range=>1, :x_range=>1, :hp_damage=>300, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
ItemInfoStatusModInv.create(:status_mod=>status_mod_cut1, :owner_id=>item_info_dagger.id, :num_of_tgt=>1, :duration=>1)
ItemInfoStatusModInv.create(:status_mod=>status_mod_cut2, :owner_id=>item_info_short_sword.id, :num_of_tgt=>1, :duration=>1)
ItemInfoStatusModInv.create(:status_mod=>status_mod_beat1, :owner_id=>item_info_club.id, :num_of_tgt=>1, :duration=>1)
family_human = Family.create(:name=>'人間', :asexual_flg=>false)
family_dragon = Family.create(:name=>'ドラゴン', :asexual_flg=>false)
family_slime = Family.create(:name=>'スライム', :asexual_flg=>true)
specie_human = Specie.create(:family=>family_human, :name=>'人間', :longevity=>80, :prolificacy=>4.0, :growth_rate=>1.0, :food_cost=>10, :str=>1000, :dex=>1000, :con=>1000, :int=>1000, :wis=>1000, :cha=>1000, :mutation_rate=>0.01, :phys_def=>400, :skill_def=>1000, :ele_fw=>0, :ele_ld=>0)
specie_dragon = Specie.create(:family=>family_dragon, :name=>'ドラゴン', :longevity=>200, :prolificacy=>2.5, :growth_rate=>0.8, :food_cost=>50, :str=>1000, :dex=>3000, :con=>1000, :int=>1500, :wis=>1500, :cha=>1000, :mutation_rate=>0.01, :phys_def=>3000, :skill_def=>2000, :ele_fw=>0, :ele_ld=>0)
specie_slime = Specie.create(:family=>family_slime, :name=>'スライム', :longevity=>10, :prolificacy=>5.0, :growth_rate=>0.5, :food_cost=>1, :str=>1000, :dex=>200, :con=>500, :int=>100, :wis=>100, :cha=>100, :mutation_rate=>0.1, :phys_def=>100, :skill_def=>100, :ele_fw=>0, :ele_ld=>0)
job_fighter = Job.create(:name=>'戦士', :growth_penalty=>0.0, :wepon_lvl=>4, :armor_lvl=>4, :str_mod=>0.2, :dex_mod=>0, :con_mod=>0.5, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
job_wizard = Job.create(:name=>'魔法使い', :growth_penalty=>0.3, :wepon_lvl=>1, :armor_lvl=>1, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0.5, :wis_mod=>0.2, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
job_priest = Job.create(:name=>'僧侶', :growth_penalty=>0.2, :wepon_lvl=>2, :armor_lvl=>3, :str_mod=>0, :dex_mod=>0, :con_mod=>0.1, :int_mod=>0.1, :wis_mod=>0.5, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
job_theif = Job.create(:name=>'盗賊', :growth_penalty=>0.1, :wepon_lvl=>3, :armor_lvl=>2, :str_mod=>0, :dex_mod=>0.5, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0.1, :skill_def_mod=>0.1)
job_ranger = Job.create(:name=>'レンジャー', :growth_penalty=>0.1, :wepon_lvl=>4, :armor_lvl=>2, :str_mod=>0.4, :dex_mod=>0.2, :con_mod=>0.1, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
skill_category_dd_fire = SkillCategory.create(:type_sym=>'dd', :element_sym=>'fire')
skill_category_dd_darkness = SkillCategory.create(:type_sym=>'dd', :element_sym=>'darkness')
skill_category_dot_fire = SkillCategory.create(:type_sym=>'dot', :element_sym=>'fire')
skill_category_dot_darkness = SkillCategory.create(:type_sym=>'dot', :element_sym=>'darkness')
skill_category_hd_water = SkillCategory.create(:type_sym=>'hd', :element_sym=>'water')
skill_category_hd_light = SkillCategory.create(:type_sym=>'hd', :element_sym=>'light')
skill_category_hot_water = SkillCategory.create(:type_sym=>'hot', :element_sym=>'water')
skill_category_hot_light = SkillCategory.create(:type_sym=>'hot', :element_sym=>'light')
skill_category_debuff_fire = SkillCategory.create(:type_sym=>'debuff', :element_sym=>'fire')
skill_category_debuff_darkness = SkillCategory.create(:type_sym=>'debuff', :element_sym=>'darkness')
skill_category_buff_water = SkillCategory.create(:type_sym=>'buff', :element_sym=>'water')
skill_category_buff_light = SkillCategory.create(:type_sym=>'buff', :element_sym=>'light')
skill_category_other_nothing = SkillCategory.create(:type_sym=>'other', :element_sym=>'nothing')
SpecieJobInv.create(:specie=>specie_human, :job_id=>job_fighter, :frequency_rate=>30)
SpecieJobInv.create(:specie=>specie_human, :job_id=>job_wizard, :frequency_rate=>20)
SpecieJobInv.create(:specie=>specie_human, :job_id=>job_priest, :frequency_rate=>20)
SpecieJobInv.create(:specie=>specie_human, :job_id=>job_theif, :frequency_rate=>15)
SpecieJobInv.create(:specie=>specie_human, :job_id=>job_ranger, :frequency_rate=>15)
SpecieJobInv.create(:specie=>specie_dragon, :job_id=>job_fighter, :frequency_rate=>30)
SpecieJobInv.create(:specie=>specie_slime, :job_id=>job_fighter, :frequency_rate=>30)
skill_taunt = Skill.create(:skill_category=>skill_category_other_nothing, :name=>'挑発', :sp_cost=>1, :research_level=>1)
skill_sheild = Skill.create(:skill_category=>skill_category_other_nothing, :name=>'盾防御', :sp_cost=>10, :research_level=>2)
skill_fire_ball = Skill.create(:skill_category=>skill_category_dd_fire, :name=>'ファイアーボール', :sp_cost=>20, :research_level=>1)
skill_poison = Skill.create(:skill_category=>skill_category_dot_darkness, :name=>'ポイズン', :sp_cost=>20, :research_level=>1)
skill_meteor_storm = Skill.create(:skill_category=>skill_category_dd_fire, :name=>'メテオストーム', :sp_cost=>50, :research_level=>2)
skill_heal = Skill.create(:skill_category=>skill_category_hd_light, :name=>'ヒール', :sp_cost=>10, :research_level=>1)
skill_regeneration = Skill.create(:skill_category=>skill_category_hot_water, :name=>'リジェネ', :sp_cost=>10, :research_level=>1)
skill_healing_rain = Skill.create(:skill_category=>skill_category_hd_water, :name=>'ヒーリングレイン', :sp_cost=>30, :research_level=>2)
skill_disarm_trap = Skill.create(:skill_category=>skill_category_other_nothing, :name=>'トラップ解除', :sp_cost=>1, :research_level=>1)
skill_evacuation = Skill.create(:skill_category=>skill_category_other_nothing, :name=>'戦闘脱出', :sp_cost=>60, :research_level=>1)
skill_double_shot = Skill.create(:skill_category=>skill_category_other_nothing, :name=>'ダブルショット', :sp_cost=>10, :research_level=>1)
skill_snare = Skill.create(:skill_category=>skill_category_debuff_darkness, :name=>'スネア', :sp_cost=>10, :research_level=>2)
skill_fire_breath = Skill.create(:skill_category=>skill_category_dd_fire, :name=>'ファイアーブレス', :sp_cost=>50, :research_level=>1)
JobSkillInv.create(:skill=>skill_taunt, :owner_id=>job_fighter.id)
JobSkillInv.create(:skill=>skill_sheild, :owner_id=>job_fighter.id)
JobSkillInv.create(:skill=>skill_fire_ball, :owner_id=>job_wizard.id)
JobSkillInv.create(:skill=>skill_poison, :owner_id=>job_wizard.id)
JobSkillInv.create(:skill=>skill_meteor_storm, :owner_id=>job_wizard.id)
JobSkillInv.create(:skill=>skill_heal, :owner_id=>job_priest.id)
JobSkillInv.create(:skill=>skill_regeneration, :owner_id=>job_priest.id)
JobSkillInv.create(:skill=>skill_healing_rain, :owner_id=>job_priest.id)
JobSkillInv.create(:skill=>skill_disarm_trap, :owner_id=>job_theif.id)
JobSkillInv.create(:skill=>skill_evacuation, :owner_id=>job_theif.id)
JobSkillInv.create(:skill=>skill_double_shot, :owner_id=>job_ranger.id)
JobSkillInv.create(:skill=>skill_snare, :owner_id=>job_ranger.id)
SpecieSkillInv.create(:skill=>skill_fire_breath, :owner_id=>specie_dragon.id)

