# coding: utf-8
houdd_user_root = HouddUser.create(:name=>'吉田松陰', :admin_flg=>true, :login_id=>'admin', :login_pw=>'admin', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
houdd_user_test1 = HouddUser.create(:name=>'有吉熊次郎', :admin_flg=>false, :login_id=>'ariyoshi', :login_pw=>'ariyoshi', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
houdd_user_test2 = HouddUser.create(:name=>'飯田正伯', :admin_flg=>false, :login_id=>'iida', :login_pw=>'iida', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'weapon', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'armor', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'potion', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_root, :symbol=>'trap', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'weapon', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'armor', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'potion', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test1, :symbol=>'trap', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'weapon', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'armor', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'potion', :level=>1, :allotment=>0, :invested_point=>0)
Research.create(:houdd_user=>houdd_user_test2, :symbol=>'trap', :level=>1, :allotment=>0, :invested_point=>0)
terrain_plain = Terrain.create(:symbol=>'plain', :name=>'平地', :food=>1, :production=>0, :money=>0, :frequency_rate=>45, :continuity_mod=>0)
terrain_woods = Terrain.create(:symbol=>'woods', :name=>'森林', :food=>0, :production=>1, :money=>0, :frequency_rate=>20, :continuity_mod=>20)
terrain_mountain = Terrain.create(:symbol=>'mountain', :name=>'山岳', :food=>0, :production=>0, :money=>0, :frequency_rate=>15, :continuity_mod=>15)
terrain_desert = Terrain.create(:symbol=>'desert', :name=>'砂漠', :food=>0, :production=>0, :money=>0, :frequency_rate=>10, :continuity_mod=>15)
terrain_sea = Terrain.create(:symbol=>'sea', :name=>'海洋', :food=>0, :production=>0, :money=>0, :frequency_rate=>10, :continuity_mod=>20)
sp_resource_iron = SpResource.create(:terrain=>terrain_mountain, :symbol=>'iron', :name=>'鉄', :food=>0, :production=>1, :money=>0, :frequency_rate=>3)
sp_resource_gold = SpResource.create(:terrain=>terrain_mountain, :symbol=>'gold', :name=>'金', :food=>0, :production=>0, :money=>3, :frequency_rate=>1)
sp_resource_fur = SpResource.create(:terrain=>terrain_woods, :symbol=>'fur', :name=>'毛皮', :food=>0, :production=>1, :money=>0, :frequency_rate=>2)
sp_resource_cotton = SpResource.create(:terrain=>terrain_plain, :symbol=>'cotton', :name=>'綿花', :food=>0, :production=>1, :money=>0, :frequency_rate=>3)
sp_resource_fish = SpResource.create(:terrain=>terrain_sea, :symbol=>'fish', :name=>'魚', :food=>2, :production=>0, :money=>0, :frequency_rate=>5)
Construction.create(:terrain=>terrain_plain, :symbol=>'farm', :name=>'農場', :food=>2, :production=>0, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_mountain, :symbol=>'mine', :name=>'鉱山', :food=>0, :production=>2, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'weapon', :name=>'武器工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'armor', :name=>'防具工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'potion', :name=>'ポーション工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_plain, :symbol=>'trading', :name=>'交易所', :food=>0, :production=>0, :money=>1, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain=>terrain_sea, :symbol=>'port', :name=>'港', :food=>2, :production=>0, :money=>0, :rq_prod_point=>50, :rq_days=>20)
MiniMap.create(:houdd_user=>houdd_user_root, :name=>'エデン', :size=>7, :hq_flg=>true, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test1, :name=>'新木', :size=>10, :hq_flg=>true, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test1, :name=>'歌里', :size=>6, :hq_flg=>false, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test2, :name=>'牛島', :size=>10, :hq_flg=>true, :type_symbol=>'plain')
MiniMap.create(:houdd_user=>houdd_user_test2, :name=>'江川', :size=>6, :hq_flg=>false, :type_symbol=>'plain')
job_fighter = Job.create(:type_symbol=>'tank', :name=>'戦士', :growth_penalty=>0.0, :weapon_lvl=>4, :armor_lvl=>4, :str_mod=>0.2, :dex_mod=>0, :con_mod=>0.5, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
job_wizard = Job.create(:type_symbol=>'attacker_r', :name=>'魔法使い', :growth_penalty=>0.3, :weapon_lvl=>1, :armor_lvl=>1, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0.5, :wis_mod=>0.2, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
job_priest = Job.create(:type_symbol=>'healer', :name=>'僧侶', :growth_penalty=>0.2, :weapon_lvl=>2, :armor_lvl=>3, :str_mod=>0, :dex_mod=>0, :con_mod=>0.1, :int_mod=>0.1, :wis_mod=>0.5, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
job_thief = Job.create(:type_symbol=>'attacker_c', :name=>'盗賊', :growth_penalty=>0.1, :weapon_lvl=>3, :armor_lvl=>2, :str_mod=>0, :dex_mod=>0.5, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0.1, :skill_def_mod=>0.1)
job_ranger = Job.create(:type_symbol=>'attacker_r', :name=>'レンジャー', :growth_penalty=>0.1, :weapon_lvl=>4, :armor_lvl=>2, :str_mod=>0.4, :dex_mod=>0.2, :con_mod=>0.1, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0)
skill_taunt = Skill.create(:type_symbol=>'other', :element_symbol=>'nothing', :name=>'挑発', :sp_cost=>1, :num_of_tgt=>5, :hit_accuracy=>99, :range=>2, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>0, :research_level=>1)
skill_shield = Skill.create(:type_symbol=>'buff', :element_symbol=>'nothing', :name=>'防御態勢', :sp_cost=>10, :num_of_tgt=>0, :hit_accuracy=>99, :range=>0, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>0, :research_level=>2)
skill_fire_ball = Skill.create(:type_symbol=>'dd', :element_symbol=>'fire', :name=>'ファイアーボール', :sp_cost=>20, :num_of_tgt=>1, :hit_accuracy=>90, :range=>2, :damage=>60, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>0, :research_level=>1)
skill_poison = Skill.create(:type_symbol=>'dot', :element_symbol=>'darkness', :name=>'ポイズン', :sp_cost=>20, :num_of_tgt=>1, :hit_accuracy=>85, :range=>2, :damage=>30, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>3, :cast_cycle=>0, :research_level=>1)
skill_meteor_storm = Skill.create(:type_symbol=>'dd', :element_symbol=>'fire', :name=>'メテオストーム', :sp_cost=>50, :num_of_tgt=>1, :hit_accuracy=>60, :range=>2, :damage=>100, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>2, :research_level=>2)
skill_heal = Skill.create(:type_symbol=>'hd', :element_symbol=>'light', :name=>'ヒール', :sp_cost=>10, :num_of_tgt=>1, :hit_accuracy=>99, :range=>2, :damage=>0, :heal=>40, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>0, :research_level=>1)
skill_regeneration = Skill.create(:type_symbol=>'hot', :element_symbol=>'light', :name=>'リジェネ', :sp_cost=>10, :num_of_tgt=>1, :hit_accuracy=>99, :range=>2, :damage=>0, :heal=>20, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>3, :cast_cycle=>0, :research_level=>1)
skill_healing_rain = Skill.create(:type_symbol=>'hd', :element_symbol=>'light', :name=>'ヒーリングレイン', :sp_cost=>30, :num_of_tgt=>5, :hit_accuracy=>60, :range=>2, :damage=>0, :heal=>80, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>2, :research_level=>2)
skill_evacuation = Skill.create(:type_symbol=>'other', :element_symbol=>'nothing', :name=>'戦闘脱出', :sp_cost=>60, :num_of_tgt=>9, :hit_accuracy=>95, :range=>2, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>0, :research_level=>2)
skill_double_shot = Skill.create(:type_symbol=>'buff', :element_symbol=>'nothing', :name=>'ダブルショット', :sp_cost=>10, :num_of_tgt=>1, :hit_accuracy=>99, :range=>1, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>0, :research_level=>1)
skill_snare = Skill.create(:type_symbol=>'debuff', :element_symbol=>'darkness', :name=>'スネア', :sp_cost=>30, :num_of_tgt=>5, :hit_accuracy=>80, :range=>2, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>-20, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>2, :cast_cycle=>1, :research_level=>2)
skill_fire_breath = Skill.create(:type_symbol=>'dd', :element_symbol=>'fire', :name=>'ファイアーブレス', :sp_cost=>5, :num_of_tgt=>5, :hit_accuracy=>60, :range=>2, :damage=>60, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :cast_cycle=>3, :research_level=>1)
skill_fly = Skill.create(:type_symbol=>'buff', :element_symbol=>'nothing', :name=>'飛行', :sp_cost=>5, :num_of_tgt=>0, :hit_accuracy=>99, :range=>1, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>20, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>20, :skill_def_mod=>10, :duration=>2, :cast_cycle=>3, :research_level=>1)
family_human = Family.create(:name=>'人間', :asexual_flg=>false)
family_dragon = Family.create(:name=>'ドラゴン', :asexual_flg=>false, :skill=>skill_fly)
family_slime = Family.create(:name=>'スライム', :asexual_flg=>true)
specie_human = Specie.create(:family=>family_human, :name=>'人間', :longevity=>60, :prolificacy=>4.0, :growth_rate=>1.0, :food_cost=>1, :str=>100, :dex=>100, :con=>100, :int=>100, :wis=>100, :cha=>100, :mutation_rate=>0.01, :phys_def=>40, :skill_def=>100, :ele_fw=>0, :ele_ld=>0)
specie_dragon = Specie.create(:family=>family_dragon, :name=>'ドラゴン', :longevity=>300, :prolificacy=>2.5, :growth_rate=>0.4, :food_cost=>4, :str=>200, :dex=>80, :con=>300, :int=>120, :wis=>120, :cha=>80, :mutation_rate=>0.01, :phys_def=>200, :skill_def=>100, :ele_fw=>0, :ele_ld=>0, :skill=>skill_fire_breath)
specie_slime = Specie.create(:family=>family_slime, :name=>'スライム', :longevity=>10, :prolificacy=>5.0, :growth_rate=>0.5, :food_cost=>1, :str=>1000, :dex=>200, :con=>500, :int=>100, :wis=>100, :cha=>100, :mutation_rate=>0.1, :phys_def=>100, :skill_def=>100, :ele_fw=>0, :ele_ld=>0)
SpecieJobInv.create(:specie=>specie_human, :job=>job_fighter, :frequency_rate=>30)
SpecieJobInv.create(:specie=>specie_human, :job=>job_wizard, :frequency_rate=>20)
SpecieJobInv.create(:specie=>specie_human, :job=>job_priest, :frequency_rate=>20)
SpecieJobInv.create(:specie=>specie_human, :job=>job_thief, :frequency_rate=>15)
SpecieJobInv.create(:specie=>specie_human, :job=>job_ranger, :frequency_rate=>15)
SpecieJobInv.create(:specie=>specie_dragon, :job=>job_fighter, :frequency_rate=>100)
SpecieJobInv.create(:specie=>specie_slime, :job=>job_fighter, :frequency_rate=>100)
JobSkillInv.create(:skill=>skill_taunt, :job=>job_fighter)
JobSkillInv.create(:skill=>skill_shield, :job=>job_fighter)
JobSkillInv.create(:skill=>skill_fire_ball, :job=>job_wizard)
JobSkillInv.create(:skill=>skill_poison, :job=>job_wizard)
JobSkillInv.create(:skill=>skill_meteor_storm, :job=>job_wizard)
JobSkillInv.create(:skill=>skill_heal, :job=>job_priest)
JobSkillInv.create(:skill=>skill_regeneration, :job=>job_priest)
JobSkillInv.create(:skill=>skill_healing_rain, :job=>job_priest)
JobSkillInv.create(:skill=>skill_evacuation, :job=>job_thief)
JobSkillInv.create(:skill=>skill_double_shot, :job=>job_ranger)
JobSkillInv.create(:skill=>skill_snare, :job=>job_ranger)
item_info_dagger = ItemInfo.create(:type_symbol=>'weapon', :element_symbol=>'nothing', :name=>'短剣', :num_of_tgt=>1, :hit_accuracy=>70, :range=>1, :damage=>50, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_human, :weight_level=>1, :max_dp=>100, :rq_prod_point=>100, :atk_cycle=>0, :research_level=>1)
item_info_short_sword = ItemInfo.create(:type_symbol=>'weapon', :element_symbol=>'nothing', :name=>'小剣', :num_of_tgt=>1, :hit_accuracy=>70, :range=>1, :damage=>100, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_human, :weight_level=>2, :max_dp=>100, :rq_prod_point=>100, :atk_cycle=>0, :research_level=>2)
item_info_club = ItemInfo.create(:type_symbol=>'weapon', :element_symbol=>'nothing', :name=>'棍棒', :num_of_tgt=>1, :hit_accuracy=>60, :range=>1, :damage=>30, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_human, :weight_level=>2, :max_dp=>50, :rq_prod_point=>30, :atk_cycle=>0, :research_level=>1)
item_info_cloth = ItemInfo.create(:type_symbol=>'armor', :element_symbol=>'nothing', :name=>'ローブ', :num_of_tgt=>1, :hit_accuracy=>0, :range=>1, :damage=>0, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>10, :skill_def_mod=>0, :duration=>0, :family=>family_human, :weight_level=>1, :max_dp=>30, :rq_prod_point=>20, :atk_cycle=>0, :research_level=>1)
ItemInfo.create(:type_symbol=>'natural_weapon', :element_symbol=>'nothing', :name=>'素手', :num_of_tgt=>1, :hit_accuracy=>70, :range=>1, :damage=>10, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_human, :weight_level=>1, :max_dp=>30, :rq_prod_point=>1, :atk_cycle=>0, :research_level=>1)
ItemInfo.create(:type_symbol=>'natural_weapon', :element_symbol=>'nothing', :name=>'爪', :num_of_tgt=>1, :hit_accuracy=>70, :range=>1, :damage=>30, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_dragon, :weight_level=>1, :max_dp=>30, :rq_prod_point=>1, :atk_cycle=>0, :research_level=>1)
ItemInfo.create(:type_symbol=>'natural_weapon', :element_symbol=>'nothing', :name=>'触手', :num_of_tgt=>1, :hit_accuracy=>70, :range=>1, :damage=>10, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_slime, :weight_level=>1, :max_dp=>30, :rq_prod_point=>1, :atk_cycle=>0, :research_level=>1)
ItemInfo.create(:type_symbol=>'trap', :element_symbol=>'nothing', :name=>'落とし穴', :num_of_tgt=>5, :hit_accuracy=>90, :range=>0, :damage=>10, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :weight_level=>1, :max_dp=>1, :rq_prod_point=>3, :atk_cycle=>0, :research_level=>1)
ItemInfo.create(:type_symbol=>'weapon', :element_symbol=>'nothing', :name=>'弓', :num_of_tgt=>1, :hit_accuracy=>60, :range=>3, :damage=>60, :heal=>0, :str_mod=>0, :dex_mod=>0, :con_mod=>0, :int_mod=>0, :wis_mod=>0, :cha_mod=>0, :ele_fw_mod=>0, :ele_ld_mod=>0, :phys_def_mod=>0, :skill_def_mod=>0, :duration=>0, :family=>family_human, :weight_level=>2, :max_dp=>100, :rq_prod_point=>100, :atk_cycle=>0, :research_level=>1)
ItemSpResourceInv.create(:item_info=>item_info_dagger, :sp_resource=>sp_resource_iron)
ItemSpResourceInv.create(:item_info=>item_info_short_sword, :sp_resource=>sp_resource_iron)



