# coding: utf-8
HouddUser.create(:name=>'吉田松陰', :admin_flg=>true, :login_id=>'admin', :login_pw=>'admin', :active_flg=>true, :allot_for_item=>34, :allot_for_const=>33, :allot_for_research=>33)
Terrain.create(:symbol=>'plain', :name=>'平地', :food=>1, :production=>0, :money=>0, :frequency_rate=>45, :continuity_mod=>0)
Terrain.create(:symbol=>'woods', :name=>'森林', :food=>0, :production=>1, :money=>0, :frequency_rate=>20, :continuity_mod=>20)
Terrain.create(:symbol=>'mountain', :name=>'山岳', :food=>0, :production=>0, :money=>0, :frequency_rate=>15, :continuity_mod=>15)
Terrain.create(:symbol=>'desert', :name=>'砂漠', :food=>0, :production=>0, :money=>0, :frequency_rate=>10, :continuity_mod=>15)
Terrain.create(:symbol=>'sea', :name=>'海洋', :food=>0, :production=>0, :money=>0, :frequency_rate=>10, :continuity_mod=>20)
SpResource.create(:terrain_id=>3, :symbol=>'iron', :name=>'鉄', :food=>0, :production=>1, :money=>0, :frequency_rate=>3)
SpResource.create(:terrain_id=>3, :symbol=>'gold', :name=>'金', :food=>0, :production=>0, :money=>3, :frequency_rate=>1)
SpResource.create(:terrain_id=>2, :symbol=>'fur', :name=>'毛皮', :food=>0, :production=>1, :money=>0, :frequency_rate=>2)
SpResource.create(:terrain_id=>1, :symbol=>'cotton', :name=>'綿花', :food=>0, :production=>1, :money=>0, :frequency_rate=>3)
SpResource.create(:terrain_id=>5, :symbol=>'fish', :name=>'魚', :food=>2, :production=>0, :money=>0, :frequency_rate=>5)
Construction.create(:terrain_id=>1, :symbol=>'farm', :name=>'農場', :food=>2, :production=>0, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain_id=>3, :symbol=>'mine', :name=>'鉱山', :food=>0, :production=>2, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain_id=>1, :symbol=>'wepon', :name=>'武器工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain_id=>1, :symbol=>'armor', :name=>'防具工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain_id=>1, :symbol=>'potion', :name=>'ポーション工房', :food=>0, :production=>1, :money=>0, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain_id=>1, :symbol=>'trading', :name=>'交易所', :food=>0, :production=>0, :money=>1, :rq_prod_point=>50, :rq_days=>20)
Construction.create(:terrain_id=>5, :symbol=>'port', :name=>'港', :food=>2, :production=>0, :money=>0, :rq_prod_point=>50, :rq_days=>20)
MiniMap.create(:houdd_user_id=>1, :name=>'エデン', :size=>7, :hq_flg=>true, :type_symbol=>'plain')
