require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BodyPartsController do

  # This should return the minimal set of attributes required to create a valid
  # BodyPart. As you add validations to BodyPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BodyPartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all body_parts as @body_parts" do
      body_part = BodyPart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:body_parts).should eq([body_part])
    end
  end

  describe "GET show" do
    it "assigns the requested body_part as @body_part" do
      body_part = BodyPart.create! valid_attributes
      get :show, {:id => body_part.to_param}, valid_session
      assigns(:body_part).should eq(body_part)
    end
  end

  describe "GET new" do
    it "assigns a new body_part as @body_part" do
      get :new, {}, valid_session
      assigns(:body_part).should be_a_new(BodyPart)
    end
  end

  describe "GET edit" do
    it "assigns the requested body_part as @body_part" do
      body_part = BodyPart.create! valid_attributes
      get :edit, {:id => body_part.to_param}, valid_session
      assigns(:body_part).should eq(body_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BodyPart" do
        expect {
          post :create, {:body_part => valid_attributes}, valid_session
        }.to change(BodyPart, :count).by(1)
      end

      it "assigns a newly created body_part as @body_part" do
        post :create, {:body_part => valid_attributes}, valid_session
        assigns(:body_part).should be_a(BodyPart)
        assigns(:body_part).should be_persisted
      end

      it "redirects to the created body_part" do
        post :create, {:body_part => valid_attributes}, valid_session
        response.should redirect_to(BodyPart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved body_part as @body_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        BodyPart.any_instance.stub(:save).and_return(false)
        post :create, {:body_part => { "name" => "invalid value" }}, valid_session
        assigns(:body_part).should be_a_new(BodyPart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BodyPart.any_instance.stub(:save).and_return(false)
        post :create, {:body_part => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested body_part" do
        body_part = BodyPart.create! valid_attributes
        # Assuming there are no other body_parts in the database, this
        # specifies that the BodyPart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BodyPart.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => body_part.to_param, :body_part => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested body_part as @body_part" do
        body_part = BodyPart.create! valid_attributes
        put :update, {:id => body_part.to_param, :body_part => valid_attributes}, valid_session
        assigns(:body_part).should eq(body_part)
      end

      it "redirects to the body_part" do
        body_part = BodyPart.create! valid_attributes
        put :update, {:id => body_part.to_param, :body_part => valid_attributes}, valid_session
        response.should redirect_to(body_part)
      end
    end

    describe "with invalid params" do
      it "assigns the body_part as @body_part" do
        body_part = BodyPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BodyPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => body_part.to_param, :body_part => { "name" => "invalid value" }}, valid_session
        assigns(:body_part).should eq(body_part)
      end

      it "re-renders the 'edit' template" do
        body_part = BodyPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BodyPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => body_part.to_param, :body_part => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested body_part" do
      body_part = BodyPart.create! valid_attributes
      expect {
        delete :destroy, {:id => body_part.to_param}, valid_session
      }.to change(BodyPart, :count).by(-1)
    end

    it "redirects to the body_parts list" do
      body_part = BodyPart.create! valid_attributes
      delete :destroy, {:id => body_part.to_param}, valid_session
      response.should redirect_to(body_parts_url)
    end
  end

end
