require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConstructionsController do

  # This should return the minimal set of attributes required to create a valid
  # Construction. As you add validations to Construction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "terrain" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConstructionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all constructions as @constructions" do
      construction = Construction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:constructions).should eq([construction])
    end
  end

  describe "GET show" do
    it "assigns the requested construction as @construction" do
      construction = Construction.create! valid_attributes
      get :show, {:id => construction.to_param}, valid_session
      assigns(:construction).should eq(construction)
    end
  end

  describe "GET new" do
    it "assigns a new construction as @construction" do
      get :new, {}, valid_session
      assigns(:construction).should be_a_new(Construction)
    end
  end

  describe "GET edit" do
    it "assigns the requested construction as @construction" do
      construction = Construction.create! valid_attributes
      get :edit, {:id => construction.to_param}, valid_session
      assigns(:construction).should eq(construction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Construction" do
        expect {
          post :create, {:construction => valid_attributes}, valid_session
        }.to change(Construction, :count).by(1)
      end

      it "assigns a newly created construction as @construction" do
        post :create, {:construction => valid_attributes}, valid_session
        assigns(:construction).should be_a(Construction)
        assigns(:construction).should be_persisted
      end

      it "redirects to the created construction" do
        post :create, {:construction => valid_attributes}, valid_session
        response.should redirect_to(Construction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved construction as @construction" do
        # Trigger the behavior that occurs when invalid params are submitted
        Construction.any_instance.stub(:save).and_return(false)
        post :create, {:construction => { "terrain" => "invalid value" }}, valid_session
        assigns(:construction).should be_a_new(Construction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Construction.any_instance.stub(:save).and_return(false)
        post :create, {:construction => { "terrain" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested construction" do
        construction = Construction.create! valid_attributes
        # Assuming there are no other constructions in the database, this
        # specifies that the Construction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Construction.any_instance.should_receive(:update_attributes).with({ "terrain" => "" })
        put :update, {:id => construction.to_param, :construction => { "terrain" => "" }}, valid_session
      end

      it "assigns the requested construction as @construction" do
        construction = Construction.create! valid_attributes
        put :update, {:id => construction.to_param, :construction => valid_attributes}, valid_session
        assigns(:construction).should eq(construction)
      end

      it "redirects to the construction" do
        construction = Construction.create! valid_attributes
        put :update, {:id => construction.to_param, :construction => valid_attributes}, valid_session
        response.should redirect_to(construction)
      end
    end

    describe "with invalid params" do
      it "assigns the construction as @construction" do
        construction = Construction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Construction.any_instance.stub(:save).and_return(false)
        put :update, {:id => construction.to_param, :construction => { "terrain" => "invalid value" }}, valid_session
        assigns(:construction).should eq(construction)
      end

      it "re-renders the 'edit' template" do
        construction = Construction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Construction.any_instance.stub(:save).and_return(false)
        put :update, {:id => construction.to_param, :construction => { "terrain" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested construction" do
      construction = Construction.create! valid_attributes
      expect {
        delete :destroy, {:id => construction.to_param}, valid_session
      }.to change(Construction, :count).by(-1)
    end

    it "redirects to the constructions list" do
      construction = Construction.create! valid_attributes
      delete :destroy, {:id => construction.to_param}, valid_session
      response.should redirect_to(constructions_url)
    end
  end

end
