require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FortressCellsController do

  # This should return the minimal set of attributes required to create a valid
  # FortressCell. As you add validations to FortressCell, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mini_map" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FortressCellsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fortress_cells as @fortress_cells" do
      fortress_cell = FortressCell.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fortress_cells).should eq([fortress_cell])
    end
  end

  describe "GET show" do
    it "assigns the requested fortress_cell as @fortress_cell" do
      fortress_cell = FortressCell.create! valid_attributes
      get :show, {:id => fortress_cell.to_param}, valid_session
      assigns(:fortress_cell).should eq(fortress_cell)
    end
  end

  describe "GET new" do
    it "assigns a new fortress_cell as @fortress_cell" do
      get :new, {}, valid_session
      assigns(:fortress_cell).should be_a_new(FortressCell)
    end
  end

  describe "GET edit" do
    it "assigns the requested fortress_cell as @fortress_cell" do
      fortress_cell = FortressCell.create! valid_attributes
      get :edit, {:id => fortress_cell.to_param}, valid_session
      assigns(:fortress_cell).should eq(fortress_cell)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FortressCell" do
        expect {
          post :create, {:fortress_cell => valid_attributes}, valid_session
        }.to change(FortressCell, :count).by(1)
      end

      it "assigns a newly created fortress_cell as @fortress_cell" do
        post :create, {:fortress_cell => valid_attributes}, valid_session
        assigns(:fortress_cell).should be_a(FortressCell)
        assigns(:fortress_cell).should be_persisted
      end

      it "redirects to the created fortress_cell" do
        post :create, {:fortress_cell => valid_attributes}, valid_session
        response.should redirect_to(FortressCell.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fortress_cell as @fortress_cell" do
        # Trigger the behavior that occurs when invalid params are submitted
        FortressCell.any_instance.stub(:save).and_return(false)
        post :create, {:fortress_cell => { "mini_map" => "invalid value" }}, valid_session
        assigns(:fortress_cell).should be_a_new(FortressCell)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FortressCell.any_instance.stub(:save).and_return(false)
        post :create, {:fortress_cell => { "mini_map" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fortress_cell" do
        fortress_cell = FortressCell.create! valid_attributes
        # Assuming there are no other fortress_cells in the database, this
        # specifies that the FortressCell created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FortressCell.any_instance.should_receive(:update_attributes).with({ "mini_map" => "" })
        put :update, {:id => fortress_cell.to_param, :fortress_cell => { "mini_map" => "" }}, valid_session
      end

      it "assigns the requested fortress_cell as @fortress_cell" do
        fortress_cell = FortressCell.create! valid_attributes
        put :update, {:id => fortress_cell.to_param, :fortress_cell => valid_attributes}, valid_session
        assigns(:fortress_cell).should eq(fortress_cell)
      end

      it "redirects to the fortress_cell" do
        fortress_cell = FortressCell.create! valid_attributes
        put :update, {:id => fortress_cell.to_param, :fortress_cell => valid_attributes}, valid_session
        response.should redirect_to(fortress_cell)
      end
    end

    describe "with invalid params" do
      it "assigns the fortress_cell as @fortress_cell" do
        fortress_cell = FortressCell.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FortressCell.any_instance.stub(:save).and_return(false)
        put :update, {:id => fortress_cell.to_param, :fortress_cell => { "mini_map" => "invalid value" }}, valid_session
        assigns(:fortress_cell).should eq(fortress_cell)
      end

      it "re-renders the 'edit' template" do
        fortress_cell = FortressCell.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FortressCell.any_instance.stub(:save).and_return(false)
        put :update, {:id => fortress_cell.to_param, :fortress_cell => { "mini_map" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fortress_cell" do
      fortress_cell = FortressCell.create! valid_attributes
      expect {
        delete :destroy, {:id => fortress_cell.to_param}, valid_session
      }.to change(FortressCell, :count).by(-1)
    end

    it "redirects to the fortress_cells list" do
      fortress_cell = FortressCell.create! valid_attributes
      delete :destroy, {:id => fortress_cell.to_param}, valid_session
      response.should redirect_to(fortress_cells_url)
    end
  end

end
