require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GenesController do

  # This should return the minimal set of attributes required to create a valid
  # Gene. As you add validations to Gene, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "specie" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GenesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all genes as @genes" do
      gene = Gene.create! valid_attributes
      get :index, {}, valid_session
      assigns(:genes).should eq([gene])
    end
  end

  describe "GET show" do
    it "assigns the requested gene as @gene" do
      gene = Gene.create! valid_attributes
      get :show, {:id => gene.to_param}, valid_session
      assigns(:gene).should eq(gene)
    end
  end

  describe "GET new" do
    it "assigns a new gene as @gene" do
      get :new, {}, valid_session
      assigns(:gene).should be_a_new(Gene)
    end
  end

  describe "GET edit" do
    it "assigns the requested gene as @gene" do
      gene = Gene.create! valid_attributes
      get :edit, {:id => gene.to_param}, valid_session
      assigns(:gene).should eq(gene)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gene" do
        expect {
          post :create, {:gene => valid_attributes}, valid_session
        }.to change(Gene, :count).by(1)
      end

      it "assigns a newly created gene as @gene" do
        post :create, {:gene => valid_attributes}, valid_session
        assigns(:gene).should be_a(Gene)
        assigns(:gene).should be_persisted
      end

      it "redirects to the created gene" do
        post :create, {:gene => valid_attributes}, valid_session
        response.should redirect_to(Gene.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gene as @gene" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gene.any_instance.stub(:save).and_return(false)
        post :create, {:gene => { "specie" => "invalid value" }}, valid_session
        assigns(:gene).should be_a_new(Gene)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gene.any_instance.stub(:save).and_return(false)
        post :create, {:gene => { "specie" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gene" do
        gene = Gene.create! valid_attributes
        # Assuming there are no other genes in the database, this
        # specifies that the Gene created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gene.any_instance.should_receive(:update_attributes).with({ "specie" => "" })
        put :update, {:id => gene.to_param, :gene => { "specie" => "" }}, valid_session
      end

      it "assigns the requested gene as @gene" do
        gene = Gene.create! valid_attributes
        put :update, {:id => gene.to_param, :gene => valid_attributes}, valid_session
        assigns(:gene).should eq(gene)
      end

      it "redirects to the gene" do
        gene = Gene.create! valid_attributes
        put :update, {:id => gene.to_param, :gene => valid_attributes}, valid_session
        response.should redirect_to(gene)
      end
    end

    describe "with invalid params" do
      it "assigns the gene as @gene" do
        gene = Gene.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gene.any_instance.stub(:save).and_return(false)
        put :update, {:id => gene.to_param, :gene => { "specie" => "invalid value" }}, valid_session
        assigns(:gene).should eq(gene)
      end

      it "re-renders the 'edit' template" do
        gene = Gene.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gene.any_instance.stub(:save).and_return(false)
        put :update, {:id => gene.to_param, :gene => { "specie" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gene" do
      gene = Gene.create! valid_attributes
      expect {
        delete :destroy, {:id => gene.to_param}, valid_session
      }.to change(Gene, :count).by(-1)
    end

    it "redirects to the genes list" do
      gene = Gene.create! valid_attributes
      delete :destroy, {:id => gene.to_param}, valid_session
      response.should redirect_to(genes_url)
    end
  end

end
