require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HouddUsersController do

  # This should return the minimal set of attributes required to create a valid
  # HouddUser. As you add validations to HouddUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HouddUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all houdd_users as @houdd_users" do
      houdd_user = HouddUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:houdd_users).should eq([houdd_user])
    end
  end

  describe "GET show" do
    it "assigns the requested houdd_user as @houdd_user" do
      houdd_user = HouddUser.create! valid_attributes
      get :show, {:id => houdd_user.to_param}, valid_session
      assigns(:houdd_user).should eq(houdd_user)
    end
  end

  describe "GET new" do
    it "assigns a new houdd_user as @houdd_user" do
      get :new, {}, valid_session
      assigns(:houdd_user).should be_a_new(HouddUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested houdd_user as @houdd_user" do
      houdd_user = HouddUser.create! valid_attributes
      get :edit, {:id => houdd_user.to_param}, valid_session
      assigns(:houdd_user).should eq(houdd_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HouddUser" do
        expect {
          post :create, {:houdd_user => valid_attributes}, valid_session
        }.to change(HouddUser, :count).by(1)
      end

      it "assigns a newly created houdd_user as @houdd_user" do
        post :create, {:houdd_user => valid_attributes}, valid_session
        assigns(:houdd_user).should be_a(HouddUser)
        assigns(:houdd_user).should be_persisted
      end

      it "redirects to the created houdd_user" do
        post :create, {:houdd_user => valid_attributes}, valid_session
        response.should redirect_to(HouddUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved houdd_user as @houdd_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        HouddUser.any_instance.stub(:save).and_return(false)
        post :create, {:houdd_user => { "name" => "invalid value" }}, valid_session
        assigns(:houdd_user).should be_a_new(HouddUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HouddUser.any_instance.stub(:save).and_return(false)
        post :create, {:houdd_user => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested houdd_user" do
        houdd_user = HouddUser.create! valid_attributes
        # Assuming there are no other houdd_users in the database, this
        # specifies that the HouddUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HouddUser.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => houdd_user.to_param, :houdd_user => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested houdd_user as @houdd_user" do
        houdd_user = HouddUser.create! valid_attributes
        put :update, {:id => houdd_user.to_param, :houdd_user => valid_attributes}, valid_session
        assigns(:houdd_user).should eq(houdd_user)
      end

      it "redirects to the houdd_user" do
        houdd_user = HouddUser.create! valid_attributes
        put :update, {:id => houdd_user.to_param, :houdd_user => valid_attributes}, valid_session
        response.should redirect_to(houdd_user)
      end
    end

    describe "with invalid params" do
      it "assigns the houdd_user as @houdd_user" do
        houdd_user = HouddUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HouddUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => houdd_user.to_param, :houdd_user => { "name" => "invalid value" }}, valid_session
        assigns(:houdd_user).should eq(houdd_user)
      end

      it "re-renders the 'edit' template" do
        houdd_user = HouddUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HouddUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => houdd_user.to_param, :houdd_user => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested houdd_user" do
      houdd_user = HouddUser.create! valid_attributes
      expect {
        delete :destroy, {:id => houdd_user.to_param}, valid_session
      }.to change(HouddUser, :count).by(-1)
    end

    it "redirects to the houdd_users list" do
      houdd_user = HouddUser.create! valid_attributes
      delete :destroy, {:id => houdd_user.to_param}, valid_session
      response.should redirect_to(houdd_users_url)
    end
  end

end
