require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemInfosController do

  # This should return the minimal set of attributes required to create a valid
  # ItemInfo. As you add validations to ItemInfo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "item_category" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemInfosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all item_infos as @item_infos" do
      item_info = ItemInfo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:item_infos).should eq([item_info])
    end
  end

  describe "GET show" do
    it "assigns the requested item_info as @item_info" do
      item_info = ItemInfo.create! valid_attributes
      get :show, {:id => item_info.to_param}, valid_session
      assigns(:item_info).should eq(item_info)
    end
  end

  describe "GET new" do
    it "assigns a new item_info as @item_info" do
      get :new, {}, valid_session
      assigns(:item_info).should be_a_new(ItemInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested item_info as @item_info" do
      item_info = ItemInfo.create! valid_attributes
      get :edit, {:id => item_info.to_param}, valid_session
      assigns(:item_info).should eq(item_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemInfo" do
        expect {
          post :create, {:item_info => valid_attributes}, valid_session
        }.to change(ItemInfo, :count).by(1)
      end

      it "assigns a newly created item_info as @item_info" do
        post :create, {:item_info => valid_attributes}, valid_session
        assigns(:item_info).should be_a(ItemInfo)
        assigns(:item_info).should be_persisted
      end

      it "redirects to the created item_info" do
        post :create, {:item_info => valid_attributes}, valid_session
        response.should redirect_to(ItemInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved item_info as @item_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemInfo.any_instance.stub(:save).and_return(false)
        post :create, {:item_info => { "item_category" => "invalid value" }}, valid_session
        assigns(:item_info).should be_a_new(ItemInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemInfo.any_instance.stub(:save).and_return(false)
        post :create, {:item_info => { "item_category" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested item_info" do
        item_info = ItemInfo.create! valid_attributes
        # Assuming there are no other item_infos in the database, this
        # specifies that the ItemInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemInfo.any_instance.should_receive(:update_attributes).with({ "item_category" => "" })
        put :update, {:id => item_info.to_param, :item_info => { "item_category" => "" }}, valid_session
      end

      it "assigns the requested item_info as @item_info" do
        item_info = ItemInfo.create! valid_attributes
        put :update, {:id => item_info.to_param, :item_info => valid_attributes}, valid_session
        assigns(:item_info).should eq(item_info)
      end

      it "redirects to the item_info" do
        item_info = ItemInfo.create! valid_attributes
        put :update, {:id => item_info.to_param, :item_info => valid_attributes}, valid_session
        response.should redirect_to(item_info)
      end
    end

    describe "with invalid params" do
      it "assigns the item_info as @item_info" do
        item_info = ItemInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => item_info.to_param, :item_info => { "item_category" => "invalid value" }}, valid_session
        assigns(:item_info).should eq(item_info)
      end

      it "re-renders the 'edit' template" do
        item_info = ItemInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => item_info.to_param, :item_info => { "item_category" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested item_info" do
      item_info = ItemInfo.create! valid_attributes
      expect {
        delete :destroy, {:id => item_info.to_param}, valid_session
      }.to change(ItemInfo, :count).by(-1)
    end

    it "redirects to the item_infos list" do
      item_info = ItemInfo.create! valid_attributes
      delete :destroy, {:id => item_info.to_param}, valid_session
      response.should redirect_to(item_infos_url)
    end
  end

end
