require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MapItemInvsController do

  # This should return the minimal set of attributes required to create a valid
  # MapItemInv. As you add validations to MapItemInv, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mini_map" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MapItemInvsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all map_item_invs as @map_item_invs" do
      map_item_inv = MapItemInv.create! valid_attributes
      get :index, {}, valid_session
      assigns(:map_item_invs).should eq([map_item_inv])
    end
  end

  describe "GET show" do
    it "assigns the requested map_item_inv as @map_item_inv" do
      map_item_inv = MapItemInv.create! valid_attributes
      get :show, {:id => map_item_inv.to_param}, valid_session
      assigns(:map_item_inv).should eq(map_item_inv)
    end
  end

  describe "GET new" do
    it "assigns a new map_item_inv as @map_item_inv" do
      get :new, {}, valid_session
      assigns(:map_item_inv).should be_a_new(MapItemInv)
    end
  end

  describe "GET edit" do
    it "assigns the requested map_item_inv as @map_item_inv" do
      map_item_inv = MapItemInv.create! valid_attributes
      get :edit, {:id => map_item_inv.to_param}, valid_session
      assigns(:map_item_inv).should eq(map_item_inv)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MapItemInv" do
        expect {
          post :create, {:map_item_inv => valid_attributes}, valid_session
        }.to change(MapItemInv, :count).by(1)
      end

      it "assigns a newly created map_item_inv as @map_item_inv" do
        post :create, {:map_item_inv => valid_attributes}, valid_session
        assigns(:map_item_inv).should be_a(MapItemInv)
        assigns(:map_item_inv).should be_persisted
      end

      it "redirects to the created map_item_inv" do
        post :create, {:map_item_inv => valid_attributes}, valid_session
        response.should redirect_to(MapItemInv.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved map_item_inv as @map_item_inv" do
        # Trigger the behavior that occurs when invalid params are submitted
        MapItemInv.any_instance.stub(:save).and_return(false)
        post :create, {:map_item_inv => { "mini_map" => "invalid value" }}, valid_session
        assigns(:map_item_inv).should be_a_new(MapItemInv)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MapItemInv.any_instance.stub(:save).and_return(false)
        post :create, {:map_item_inv => { "mini_map" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested map_item_inv" do
        map_item_inv = MapItemInv.create! valid_attributes
        # Assuming there are no other map_item_invs in the database, this
        # specifies that the MapItemInv created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MapItemInv.any_instance.should_receive(:update_attributes).with({ "mini_map" => "" })
        put :update, {:id => map_item_inv.to_param, :map_item_inv => { "mini_map" => "" }}, valid_session
      end

      it "assigns the requested map_item_inv as @map_item_inv" do
        map_item_inv = MapItemInv.create! valid_attributes
        put :update, {:id => map_item_inv.to_param, :map_item_inv => valid_attributes}, valid_session
        assigns(:map_item_inv).should eq(map_item_inv)
      end

      it "redirects to the map_item_inv" do
        map_item_inv = MapItemInv.create! valid_attributes
        put :update, {:id => map_item_inv.to_param, :map_item_inv => valid_attributes}, valid_session
        response.should redirect_to(map_item_inv)
      end
    end

    describe "with invalid params" do
      it "assigns the map_item_inv as @map_item_inv" do
        map_item_inv = MapItemInv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MapItemInv.any_instance.stub(:save).and_return(false)
        put :update, {:id => map_item_inv.to_param, :map_item_inv => { "mini_map" => "invalid value" }}, valid_session
        assigns(:map_item_inv).should eq(map_item_inv)
      end

      it "re-renders the 'edit' template" do
        map_item_inv = MapItemInv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MapItemInv.any_instance.stub(:save).and_return(false)
        put :update, {:id => map_item_inv.to_param, :map_item_inv => { "mini_map" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested map_item_inv" do
      map_item_inv = MapItemInv.create! valid_attributes
      expect {
        delete :destroy, {:id => map_item_inv.to_param}, valid_session
      }.to change(MapItemInv, :count).by(-1)
    end

    it "redirects to the map_item_invs list" do
      map_item_inv = MapItemInv.create! valid_attributes
      delete :destroy, {:id => map_item_inv.to_param}, valid_session
      response.should redirect_to(map_item_invs_url)
    end
  end

end
