require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MiniMapRoadsController do

  # This should return the minimal set of attributes required to create a valid
  # MiniMapRoad. As you add validations to MiniMapRoad, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "start_mini_map_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MiniMapRoadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mini_map_roads as @mini_map_roads" do
      mini_map_road = MiniMapRoad.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mini_map_roads).should eq([mini_map_road])
    end
  end

  describe "GET show" do
    it "assigns the requested mini_map_road as @mini_map_road" do
      mini_map_road = MiniMapRoad.create! valid_attributes
      get :show, {:id => mini_map_road.to_param}, valid_session
      assigns(:mini_map_road).should eq(mini_map_road)
    end
  end

  describe "GET new" do
    it "assigns a new mini_map_road as @mini_map_road" do
      get :new, {}, valid_session
      assigns(:mini_map_road).should be_a_new(MiniMapRoad)
    end
  end

  describe "GET edit" do
    it "assigns the requested mini_map_road as @mini_map_road" do
      mini_map_road = MiniMapRoad.create! valid_attributes
      get :edit, {:id => mini_map_road.to_param}, valid_session
      assigns(:mini_map_road).should eq(mini_map_road)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MiniMapRoad" do
        expect {
          post :create, {:mini_map_road => valid_attributes}, valid_session
        }.to change(MiniMapRoad, :count).by(1)
      end

      it "assigns a newly created mini_map_road as @mini_map_road" do
        post :create, {:mini_map_road => valid_attributes}, valid_session
        assigns(:mini_map_road).should be_a(MiniMapRoad)
        assigns(:mini_map_road).should be_persisted
      end

      it "redirects to the created mini_map_road" do
        post :create, {:mini_map_road => valid_attributes}, valid_session
        response.should redirect_to(MiniMapRoad.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mini_map_road as @mini_map_road" do
        # Trigger the behavior that occurs when invalid params are submitted
        MiniMapRoad.any_instance.stub(:save).and_return(false)
        post :create, {:mini_map_road => { "start_mini_map_id" => "invalid value" }}, valid_session
        assigns(:mini_map_road).should be_a_new(MiniMapRoad)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MiniMapRoad.any_instance.stub(:save).and_return(false)
        post :create, {:mini_map_road => { "start_mini_map_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mini_map_road" do
        mini_map_road = MiniMapRoad.create! valid_attributes
        # Assuming there are no other mini_map_roads in the database, this
        # specifies that the MiniMapRoad created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MiniMapRoad.any_instance.should_receive(:update_attributes).with({ "start_mini_map_id" => "1" })
        put :update, {:id => mini_map_road.to_param, :mini_map_road => { "start_mini_map_id" => "1" }}, valid_session
      end

      it "assigns the requested mini_map_road as @mini_map_road" do
        mini_map_road = MiniMapRoad.create! valid_attributes
        put :update, {:id => mini_map_road.to_param, :mini_map_road => valid_attributes}, valid_session
        assigns(:mini_map_road).should eq(mini_map_road)
      end

      it "redirects to the mini_map_road" do
        mini_map_road = MiniMapRoad.create! valid_attributes
        put :update, {:id => mini_map_road.to_param, :mini_map_road => valid_attributes}, valid_session
        response.should redirect_to(mini_map_road)
      end
    end

    describe "with invalid params" do
      it "assigns the mini_map_road as @mini_map_road" do
        mini_map_road = MiniMapRoad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MiniMapRoad.any_instance.stub(:save).and_return(false)
        put :update, {:id => mini_map_road.to_param, :mini_map_road => { "start_mini_map_id" => "invalid value" }}, valid_session
        assigns(:mini_map_road).should eq(mini_map_road)
      end

      it "re-renders the 'edit' template" do
        mini_map_road = MiniMapRoad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MiniMapRoad.any_instance.stub(:save).and_return(false)
        put :update, {:id => mini_map_road.to_param, :mini_map_road => { "start_mini_map_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mini_map_road" do
      mini_map_road = MiniMapRoad.create! valid_attributes
      expect {
        delete :destroy, {:id => mini_map_road.to_param}, valid_session
      }.to change(MiniMapRoad, :count).by(-1)
    end

    it "redirects to the mini_map_roads list" do
      mini_map_road = MiniMapRoad.create! valid_attributes
      delete :destroy, {:id => mini_map_road.to_param}, valid_session
      response.should redirect_to(mini_map_roads_url)
    end
  end

end
