require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpecieJobInvsController do

  # This should return the minimal set of attributes required to create a valid
  # SpecieJobInv. As you add validations to SpecieJobInv, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "specie" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpecieJobInvsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all specie_job_invs as @specie_job_invs" do
      specie_job_inv = SpecieJobInv.create! valid_attributes
      get :index, {}, valid_session
      assigns(:specie_job_invs).should eq([specie_job_inv])
    end
  end

  describe "GET show" do
    it "assigns the requested specie_job_inv as @specie_job_inv" do
      specie_job_inv = SpecieJobInv.create! valid_attributes
      get :show, {:id => specie_job_inv.to_param}, valid_session
      assigns(:specie_job_inv).should eq(specie_job_inv)
    end
  end

  describe "GET new" do
    it "assigns a new specie_job_inv as @specie_job_inv" do
      get :new, {}, valid_session
      assigns(:specie_job_inv).should be_a_new(SpecieJobInv)
    end
  end

  describe "GET edit" do
    it "assigns the requested specie_job_inv as @specie_job_inv" do
      specie_job_inv = SpecieJobInv.create! valid_attributes
      get :edit, {:id => specie_job_inv.to_param}, valid_session
      assigns(:specie_job_inv).should eq(specie_job_inv)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpecieJobInv" do
        expect {
          post :create, {:specie_job_inv => valid_attributes}, valid_session
        }.to change(SpecieJobInv, :count).by(1)
      end

      it "assigns a newly created specie_job_inv as @specie_job_inv" do
        post :create, {:specie_job_inv => valid_attributes}, valid_session
        assigns(:specie_job_inv).should be_a(SpecieJobInv)
        assigns(:specie_job_inv).should be_persisted
      end

      it "redirects to the created specie_job_inv" do
        post :create, {:specie_job_inv => valid_attributes}, valid_session
        response.should redirect_to(SpecieJobInv.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved specie_job_inv as @specie_job_inv" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecieJobInv.any_instance.stub(:save).and_return(false)
        post :create, {:specie_job_inv => { "specie" => "invalid value" }}, valid_session
        assigns(:specie_job_inv).should be_a_new(SpecieJobInv)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecieJobInv.any_instance.stub(:save).and_return(false)
        post :create, {:specie_job_inv => { "specie" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested specie_job_inv" do
        specie_job_inv = SpecieJobInv.create! valid_attributes
        # Assuming there are no other specie_job_invs in the database, this
        # specifies that the SpecieJobInv created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpecieJobInv.any_instance.should_receive(:update_attributes).with({ "specie" => "" })
        put :update, {:id => specie_job_inv.to_param, :specie_job_inv => { "specie" => "" }}, valid_session
      end

      it "assigns the requested specie_job_inv as @specie_job_inv" do
        specie_job_inv = SpecieJobInv.create! valid_attributes
        put :update, {:id => specie_job_inv.to_param, :specie_job_inv => valid_attributes}, valid_session
        assigns(:specie_job_inv).should eq(specie_job_inv)
      end

      it "redirects to the specie_job_inv" do
        specie_job_inv = SpecieJobInv.create! valid_attributes
        put :update, {:id => specie_job_inv.to_param, :specie_job_inv => valid_attributes}, valid_session
        response.should redirect_to(specie_job_inv)
      end
    end

    describe "with invalid params" do
      it "assigns the specie_job_inv as @specie_job_inv" do
        specie_job_inv = SpecieJobInv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecieJobInv.any_instance.stub(:save).and_return(false)
        put :update, {:id => specie_job_inv.to_param, :specie_job_inv => { "specie" => "invalid value" }}, valid_session
        assigns(:specie_job_inv).should eq(specie_job_inv)
      end

      it "re-renders the 'edit' template" do
        specie_job_inv = SpecieJobInv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecieJobInv.any_instance.stub(:save).and_return(false)
        put :update, {:id => specie_job_inv.to_param, :specie_job_inv => { "specie" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested specie_job_inv" do
      specie_job_inv = SpecieJobInv.create! valid_attributes
      expect {
        delete :destroy, {:id => specie_job_inv.to_param}, valid_session
      }.to change(SpecieJobInv, :count).by(-1)
    end

    it "redirects to the specie_job_invs list" do
      specie_job_inv = SpecieJobInv.create! valid_attributes
      delete :destroy, {:id => specie_job_inv.to_param}, valid_session
      response.should redirect_to(specie_job_invs_url)
    end
  end

end
