require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StatusModsController do

  # This should return the minimal set of attributes required to create a valid
  # StatusMod. As you add validations to StatusMod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatusModsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all status_mods as @status_mods" do
      status_mod = StatusMod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:status_mods).should eq([status_mod])
    end
  end

  describe "GET show" do
    it "assigns the requested status_mod as @status_mod" do
      status_mod = StatusMod.create! valid_attributes
      get :show, {:id => status_mod.to_param}, valid_session
      assigns(:status_mod).should eq(status_mod)
    end
  end

  describe "GET new" do
    it "assigns a new status_mod as @status_mod" do
      get :new, {}, valid_session
      assigns(:status_mod).should be_a_new(StatusMod)
    end
  end

  describe "GET edit" do
    it "assigns the requested status_mod as @status_mod" do
      status_mod = StatusMod.create! valid_attributes
      get :edit, {:id => status_mod.to_param}, valid_session
      assigns(:status_mod).should eq(status_mod)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StatusMod" do
        expect {
          post :create, {:status_mod => valid_attributes}, valid_session
        }.to change(StatusMod, :count).by(1)
      end

      it "assigns a newly created status_mod as @status_mod" do
        post :create, {:status_mod => valid_attributes}, valid_session
        assigns(:status_mod).should be_a(StatusMod)
        assigns(:status_mod).should be_persisted
      end

      it "redirects to the created status_mod" do
        post :create, {:status_mod => valid_attributes}, valid_session
        response.should redirect_to(StatusMod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved status_mod as @status_mod" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusMod.any_instance.stub(:save).and_return(false)
        post :create, {:status_mod => { "name" => "invalid value" }}, valid_session
        assigns(:status_mod).should be_a_new(StatusMod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusMod.any_instance.stub(:save).and_return(false)
        post :create, {:status_mod => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested status_mod" do
        status_mod = StatusMod.create! valid_attributes
        # Assuming there are no other status_mods in the database, this
        # specifies that the StatusMod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StatusMod.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => status_mod.to_param, :status_mod => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested status_mod as @status_mod" do
        status_mod = StatusMod.create! valid_attributes
        put :update, {:id => status_mod.to_param, :status_mod => valid_attributes}, valid_session
        assigns(:status_mod).should eq(status_mod)
      end

      it "redirects to the status_mod" do
        status_mod = StatusMod.create! valid_attributes
        put :update, {:id => status_mod.to_param, :status_mod => valid_attributes}, valid_session
        response.should redirect_to(status_mod)
      end
    end

    describe "with invalid params" do
      it "assigns the status_mod as @status_mod" do
        status_mod = StatusMod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusMod.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_mod.to_param, :status_mod => { "name" => "invalid value" }}, valid_session
        assigns(:status_mod).should eq(status_mod)
      end

      it "re-renders the 'edit' template" do
        status_mod = StatusMod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusMod.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_mod.to_param, :status_mod => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested status_mod" do
      status_mod = StatusMod.create! valid_attributes
      expect {
        delete :destroy, {:id => status_mod.to_param}, valid_session
      }.to change(StatusMod, :count).by(-1)
    end

    it "redirects to the status_mods list" do
      status_mod = StatusMod.create! valid_attributes
      delete :destroy, {:id => status_mod.to_param}, valid_session
      response.should redirect_to(status_mods_url)
    end
  end

end
