require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrialsController do

  # This should return the minimal set of attributes required to create a valid
  # Trial. As you add validations to Trial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mini_map" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all trials as @trials" do
      trial = Trial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trials).should eq([trial])
    end
  end

  describe "GET show" do
    it "assigns the requested trial as @trial" do
      trial = Trial.create! valid_attributes
      get :show, {:id => trial.to_param}, valid_session
      assigns(:trial).should eq(trial)
    end
  end

  describe "GET new" do
    it "assigns a new trial as @trial" do
      get :new, {}, valid_session
      assigns(:trial).should be_a_new(Trial)
    end
  end

  describe "GET edit" do
    it "assigns the requested trial as @trial" do
      trial = Trial.create! valid_attributes
      get :edit, {:id => trial.to_param}, valid_session
      assigns(:trial).should eq(trial)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trial" do
        expect {
          post :create, {:trial => valid_attributes}, valid_session
        }.to change(Trial, :count).by(1)
      end

      it "assigns a newly created trial as @trial" do
        post :create, {:trial => valid_attributes}, valid_session
        assigns(:trial).should be_a(Trial)
        assigns(:trial).should be_persisted
      end

      it "redirects to the created trial" do
        post :create, {:trial => valid_attributes}, valid_session
        response.should redirect_to(Trial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trial as @trial" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trial.any_instance.stub(:save).and_return(false)
        post :create, {:trial => { "mini_map" => "invalid value" }}, valid_session
        assigns(:trial).should be_a_new(Trial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trial.any_instance.stub(:save).and_return(false)
        post :create, {:trial => { "mini_map" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trial" do
        trial = Trial.create! valid_attributes
        # Assuming there are no other trials in the database, this
        # specifies that the Trial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trial.any_instance.should_receive(:update_attributes).with({ "mini_map" => "" })
        put :update, {:id => trial.to_param, :trial => { "mini_map" => "" }}, valid_session
      end

      it "assigns the requested trial as @trial" do
        trial = Trial.create! valid_attributes
        put :update, {:id => trial.to_param, :trial => valid_attributes}, valid_session
        assigns(:trial).should eq(trial)
      end

      it "redirects to the trial" do
        trial = Trial.create! valid_attributes
        put :update, {:id => trial.to_param, :trial => valid_attributes}, valid_session
        response.should redirect_to(trial)
      end
    end

    describe "with invalid params" do
      it "assigns the trial as @trial" do
        trial = Trial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trial.any_instance.stub(:save).and_return(false)
        put :update, {:id => trial.to_param, :trial => { "mini_map" => "invalid value" }}, valid_session
        assigns(:trial).should eq(trial)
      end

      it "re-renders the 'edit' template" do
        trial = Trial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trial.any_instance.stub(:save).and_return(false)
        put :update, {:id => trial.to_param, :trial => { "mini_map" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trial" do
      trial = Trial.create! valid_attributes
      expect {
        delete :destroy, {:id => trial.to_param}, valid_session
      }.to change(Trial, :count).by(-1)
    end

    it "redirects to the trials list" do
      trial = Trial.create! valid_attributes
      delete :destroy, {:id => trial.to_param}, valid_session
      response.should redirect_to(trials_url)
    end
  end

end
